--------------------------------------------------------------------------------
-- License
--------------------------------------------------------------------------------

-- Copyright (c) 2024 Klayton Kowalski

-- This software is provided 'as-is', without any express or implied warranty.
-- In no event will the authors be held liable for any damages arising from the use of this software.

-- Permission is granted to anyone to use this software for any purpose,
-- including commercial applications, and to alter it and redistribute it freely,
-- subject to the following restrictions:

-- 1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software.
--    If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.

-- 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

-- 3. This notice may not be removed or altered from any source distribution.

--------------------------------------------------------------------------------
-- Information
--------------------------------------------------------------------------------

-- GitHub: https://github.com/klaytonkowalski/library-defold-rendy

--------------------------------------------------------------------------------
-- Dependencies
--------------------------------------------------------------------------------

local rendy = require "rendy.rendy"

--------------------------------------------------------------------------------
-- Constants
--------------------------------------------------------------------------------

local acquire_input_focus = hash("acquire_input_focus")

local rendy_top_left = hash("/rendy_top_left")
local rendy_top_right = hash("/rendy_top_right")
local rendy_bottom_left = hash("/rendy_bottom_left")

--------------------------------------------------------------------------------
-- Engine Functions
--------------------------------------------------------------------------------

function init(self)
	msg.post(msg.url(), acquire_input_focus)
	go.animate(msg.url(nil, rendy_top_left, "script"), "zoom", go.PLAYBACK_LOOP_PINGPONG, 4, go.EASING_INOUTQUAD, 10)
	go.animate(msg.url(nil, rendy_top_right, "script"), "zoom", go.PLAYBACK_LOOP_PINGPONG, 4, go.EASING_INOUTQUAD, 10)
	go.animate(msg.url(nil, rendy_bottom_left, "script"), "zoom", go.PLAYBACK_LOOP_PINGPONG, 4, go.EASING_INOUTQUAD, 10)
end

function on_input(self, action_id, action)
	if not action_id then
		
	end
end